---
name: "HPS121"
title: "Unit Schedule"
description: "HPS121 - Introduction to Psychology B: Individual and Social Development"
output:
  html_document
---

| Week | Commencing | Topic | Special Learning Activities | Assessment Due Date |
|------|------------|-------|-----------------------------|---------------------|
| 1 | 7 Mar 22 | Human Development | Class 1: Developmental Psychology<br />Seminar 1: Lab Report (Assessing the core readings) | 
| 2 | 14 Mar 22 |  | Seminar 2: Lab Report (Conducting a literature review) | 
| 3 | 21 Mar 22 | Personality | Class 2: Personality<br />Seminar 3: Lab Report (Introduction Section) | 
| 4 | 28 Mar 22 |  | Seminar 4: Lab Report (Method Section) | 
| 5 | 4 Apr 22 | Psychological Disorders | Class 3: Psychological Disorders<br />Seminar 5: Developmental Psychology Revision | AT1 due by 8:00pm 7 April 22
| 6 | 11 Apr 22 |  | Seminar 6: Lab Report (Results Section) | 
| 7 | 25 Apr 22 | Psychological Treatment | Class 4: Psychological Treatment<br />Seminar 7: Lab Report (Discussion and putting it all together) | 
| 8 | 2 May 22 |  | Seminar 8: Personality | 
| 9 | 9 May 22 | Social Psychology | Class 5: Social Psychology<br />Seminar 9: Psychological Disorders Revision | AT2 due by 8:00pm 12 May 22 |
| 10 | 16 May 22 |  | Seminar10: Psychological Treatment Revision | 
| 11 | 23 May 22 | Indigenous and Cross-Cultural Psychology | Class 6: Indigenous and Cross-Cultural Psychology<br />Seminar 11: Social Psychology Revision |