---
title: "Reading List"
description: |
  HPS121 - Introduction to Psychology: Individual and Social Development
---

| Topic	| Title	| Notes |
|-------|-------|-------|
| Prescribed | [How to write psychology research reports and assignments](http://resourcelists.lib.deakin.edu.au/items/345bc52c-6b11-4870-bdb1-7740b0b47899.html) | |
| 1 | [Developmental theories](http://resourcelists.lib.deakin.edu.au/items/923FD1C1-4404-8499-1872-86AC50639B25.html) | Chapter 2, Developmental theories, students to begin reading at section Psychosocial theory (Erik Erikson 1902-1990) |
| 1 |	[Social Learning](http://resourcelists.lib.deakin.edu.au/items/BCEFCCDA-EACE-DC00-3C0B-922C6A37D6B7.html)	| Chapter 9 |
| 1 |	[Moral Development](http://resourcelists.lib.deakin.edu.au/items/96B76F94-AFA0-9BFD-9505-2C1CC702B3DD.html)	| Chapter 8 |
| 1 |	[Rethinking the biopsychosocial model of health: Understanding health as a dynamic system](http://resourcelists.lib.deakin.edu.au/items/BB23A9F1-54C7-2CFD-1A12-3922D5DA472F.html)	| |
| 2 |	[The Psychodynamic Perspective](http://resourcelists.lib.deakin.edu.au/items/02527699-29E0-2C09-49DA-02156516E0EF.html)	| |
| 2 |	[Personality Traits](http://resourcelists.lib.deakin.edu.au/items/3080D220-42BA-A302-A853-639598E7B1EF.html) | |
| 2 |	[Personality Assessment](http://resourcelists.lib.deakin.edu.au/items/4A20C70D-AE02-902A-BC99-DDB0A441A0F4.html) | |
| 3 |	[Psychological Disorders](http://resourcelists.lib.deakin.edu.au/items/BC26A909-50BE-4007-96D8-0ECF784ADD0D.html)	| E-book has limited concurrent users. If in use try again later. |
| 4 |	[Reducing Disorder by Confronting It: Psychotherapy](http://resourcelists.lib.deakin.edu.au/items/50E6D5D6-BEEA-99D0-343B-C2726E4F87D6.html) |	Chapter 18.1, 18.3, 18.4 |
| 4 |	[Types of treatment](http://resourcelists.lib.deakin.edu.au/items/4167A3DB-DE92-F44C-23E4-0173AE806644.html)	| |
| 4 |	[Why have psychologists been slow to adopt telehealth?](http://resourcelists.lib.deakin.edu.au/items/fbb333cb-29ba-4b9b-8c9c-63810007de2b.html)	| |
| 5 |	[Psychology in Our Social Lives](http://resourcelists.lib.deakin.edu.au/items/C955C9D0-CB8B-84C3-6F21-D76674DA0891.html)	| |
| 6 |	[Extracts from Cross-Cultural Psychology : Research and Applications](http://resourcelists.lib.deakin.edu.au/items/6B4BDD48-FBE7-4EAB-0F7F-70FAB4341E50.html)	| Chapter 1, pages 1-4 and 18-20 |
| 6 |	[Chapter 1](http://resourcelists.lib.deakin.edu.au/items/528877F0-0986-E94F-3477-6C1AC8D8D166.html)	| Chapter 1, pages 3-24 |