---
title: "Topic 1: Developmental Psychology"
output: distill::distill_article
---

Psychodynamic Theory
	
	- An investigation into how our life experiences have impacted behaviour
	- Still used in some form today to examine the interaction of drives and forces within a person and between the different structures of their personality.
	- Contributors include Freud, Jung, Adler, and Erikson

Basic Assumptions
	
	- Behaviour and feelings controlled by unconscious motives.
	- Childhood experiences are considered the root cause of how we develop as adults and come to see the world.
	- All behaviour is intentional, even if only at an unconscious level.
	- Personality = id + ego + superego
	- ID (Instinctual Drives)
	  - Eros = Sex drive and life instinct
		- Thanatos = Aggressive drive and death instinct.
	- Ego (Conscious Mind)
	- Unconscious Mind (id and superego) can be in constant conflict with ego
	- Instinctual drives are altered at different times during childhood, which then contribute towards shaping our personality.

Sigmund Freud (1856-1939)

Drives were considered innate and constantly felt, with the core principle of Psychodynamic Theory concerning the management of the conflict between these drives.

The id consists of all inherited personality, and is the part of the psyche where impulse, both pleasure (sex life) and displeasure (death instincts) reside. The id is driven by instant gratification (pleasure principle), in seeking pleasure and avoiding displeasure.

The ego is the logical mediator between the id and the reality of life. The 'reality principle' is associated with delayed gratification.

The superego regulates the adherence to societal norms, and it's purpose is to manage the id's impulses. Composed of two systems, the conscience and the 'ideal self". The conscience punishes the ego through guilt, while the ideal self is our model of how we ought to be.

The relationship between these centres is considered to be the source of inner conflict, and the balance of impulsive behaviour and meeting needs with the expectations of ourselves and society.

Psychosexual Theory

Freud's theory of development consists of 5 stages:

	1. Oral Stage: where the mouth is the primary erogenous zone. Through the acts of feeding and gathering information about their environment. It was considered that the risk of fixation was a risk to improperly cared for infants.

	2. Anal Stage: The child derives pleasure from the expulsion of waste. Threats to development here through a lack of control are thought to explain anal retentive (neat), or anal expensive (messy) personality traits.

	3. Phallic Stage: This stage points to the child becoming aware of their genitals, and gave rise to Freud's explanation of the Oedipus Complex. It was also considered only to effect boys. The Electra Complex was a postulated theory refuted by Freud.

	4. Latency Period: Period from 6 years old to puberty where focus is aimed at a child's need to play and interact with same sense peers.

	5. Genital Stage: The onset of puberty

Evaluation of the Theory

- Primarily a theoretical construct, lacking empirical evidence.
- Freud worked primarily with adults in his practice.
- Almost a pseudo science a dream analysts were able to focus on their own interpretations, through discussion with clients, and refute any views that did not uphold their own.

Psychosocial Theory (Erikson)

- 8 stages of development from birth to adulthood.

- All stages in a specific order, containing a crisis at each stage. needing resolution before the next stage.

- Failure to resolve the crisis at each stage would effect child's development at late stages.


| Developmental Stage              | Developmental Crisis           |
| -------------------------------- | ------------------------------ |
| Birth - 1 year                   | Trust Vs Mistrust              |
| 1 - 3 years                      | Autonomy vs Shame              |
| 3 - 6 years                      | Initiative vs Guilt            |
| 6 years to adolescence           | Industry vs Inferiority        |
| Adolescence (10 - 20 years)      | Identity vs Identity Diffusion |
| Young Adulthood (20 - 40 years)  | Intimacy vs Isolation          |
| Middle Adulthood (40 - 60 years) | Gernerativity vs Stagnation    |
| Old Age (60+ years)              | Integrity vs Despair           |

1. Trust vs. Mistrust (birth to 1 year): Development of trust as a consequence of treatment.

2. Autonomy vs. Shame (1 - 3 years): learning to negotiate with parents to have needs and wants met. Development of a sense of independence.

3. Initiative vs. Guilt (3- 6 years): Learning how to play with others, lead and follow, as opposed to prevention from joining in through guilt or fear.

4. Industry vs. Inferiority (6 years to adolescence): Building of skills around play and obeying rules. Mastery of social skills, and self discipline. A mistrusting child will develop defeat and inferiority.

5. Identity vs. Identity Diffusion(10-20 yrs): Children experiment with defiance and rule breaking. Also the time when a child will develop their sense of self and identity.

6. Intimacy Vs. Isolation(so-40 yrs): A period of building long standing friendships and relationships.

7. Generativity vs. Self Absorbtion (40-60 years): Becoming productive in society and setting an example for future generations. Developing interest in parenthood.

8. Integrity vs. Despair (60 + years): Acknowledgement of prior achievement of the other stages and the recognition of integrity, as opposed to despair should one or more of the crises at previous stages not be resolved.

Evaluation of Theory

- While insightful and plausible, no empirical evidence was gathered to develop theory.
- Erikson worked mainly with children, so his theory was based on this experience.
- The teen crisis was used to refer to the sensitivity of developmental meds at each stage, rather than a catastrophic event.
- Emphasises the role of psycological and social influence a development throughout a lifetime.

Behavioural (learning)Theories

Identified by many as being relevant regardless of age, and not being isolated to a particular "stage". The focus instead, is on stimulus/response and looking for predictable patterns of behaviour.

Behaviourism (Watson)

**Behaviourism Core Concepts:**

1. The Blank Slate: Children enter the world as a blank slate with ability to learn based on their
	environment.

2. Behavioural Focus: Concentrates on observable behaviours, and discovery of environmental stimuli responsible.

3. Environmental Determinism: A individuals behaviour is shaped by their environment rather than 'free will'.

4. Conditioning: The main process through which we learn.

Pavlov's dogs: Classical Conditioning

Operant Conditioning (Skinner's pigeons)

Social Modelling or Social learning theory (Bandura)

Observation (of consequences), imitation, and modelling as demonstrated via the Bobo doll experiment (modelling and imitation of aggression). The experiment found that observations of aggressive behaviour influenced children towards acceptance (TAC ad).

Evaluation of behavioural theories

- Empirical approach (Bobo experiment)
- Attempts to demonstrate cause and effect
- Neglects rational thought processes.
- Does not address behaviours that are present in the absence of conditioning.
- Demonstration of hostile more likely to develop a hostile bias in future interactions.
- Some suggest that the setting is artificial. Demonstrating behaviours that were thought to be expected.
- Fails to determine if behaviours would be generalised in other scenarios.
- Primary focus on environmental factors, ignoring genetic disposition, rex based neurological differences.


Environment

Ethological Theory
Stresses that behaviour is strongly influenced by biology and evolution while also being mediated by sensitive periods. Emotions and thinking is heavily influenced by inherited factors.

Charles Darwin's theory of evolution underpins this theory, stating that more than just physical attributes (hair and eye colour) influence us.

  - Bioecological Model
	- Life Course theory

Cognitive development theories
  
  - Piaget's CDT
  - Sociocultural Theory Development (Vygotsky)
  - Info processing approach (Siegler)