---
title: "Topic 3: Psychological Disorders"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

incidence of a disorder

Prevalence

both new and previously existing cases

What is ‘abnormal’?

no agreed-upon benchmarks

distress, dysfunction and deviance—tend to govern decisions about abnormality

personal distress is neither

necessary nor sufficient to define abnormality

Figure 15.2

abnormal behaviour as behaviour that is personally distressing, personally dysfunctional and/or so culturally deviant that other people judge it to be inappropriate or maladaptive.

Table 15.1

International Classification of Diseases and Health-related Problems (ICD)

pages of history are filled with accounts of prominent people who suffered from psychological disorders

According to the vulnerability-stress model (sometimes called the diathesis- stress model; Figure 15.6 ), each of us has some degree of vulnerability (ranging from very low to very high) for developing a psychological disorder, given sufficient stress.

Figure 15.6

anxiety , a natural response to perceived threat.

Anxiety responses have four components: (1) a subjective-emotional component, including feelings of fear and apprehension; (2) a cognitive component, including worrisome thoughts and a sense of inability to cope; (3) physiological responses, including increased heart rate and blood pressure, muscle tension, rapid breathing, nausea or dry mouth; and (4) behavioural responses, such as avoidance of certain situations and impaired performance on other tasks (Barlow, 2002; Figure 15.7 )

However, in anxiety and related disorders , the frequency and intensity of anxiety responses are out of proportion to the situations that trigger them.

Figure 15.7

Phobic disorders

Phobias are strong and irrational fears of certain objects or situations.

Agoraphobia involves an excessive fear of situations such as using public transport, being in a crowd or being outside the home.

The individual fears these situations because they believe that escape would be difficult, or help unavailable if panic-like symptoms or other distressing, embarrassing or incapacitating events were to occur (e.g. incontinence).

social phobia fear social situations in which they may be negatively evaluated by others (e.g. meeting new people, or public speaking).

Specific phobias are characterised by an intense fear of a specific object or situation (e.g. dogs, snakes, spiders, aeroplanes, lifts, enclosed spaces, water, or blood and injections).

Phobias can develop at any point in life, but they often arise during childhood. Many social phobias evolve out of extreme shyness during childhood (Beidel & T urner, 2007). Phobias may also begin in adolescence or early adulthood. Once phobias develop, they seldom go away on their own, and they may broaden and intensify over time

The degree of impairment caused by a phobia depends in part on how often the phobic stimulus is encountered in the individual’s normal activities

Panic disorder

panic disorder occur suddenly and unpredictably, and they are much more intense.

panic attacks usually occur out of the blue and in the absence of any identifiable stimulus.

panic attacks occur predictably, in the presence of the fear object

followed by psychological or behavioural problems, such as persistent, intense worry and fear about experiencing further panic attacks, and/or behavioural changes aimed at reducing the likelihood of their occurrence.

Many people who experience recurrent panic attacks develop agoraphobia.

Panic disorders with or without agoraphobia tend to appear in late adolescence or early adulthood and affect about 5 per cent of the Australian population

Generalised anxiety disorder

generalised anxiety disorder is a chronic (ongoing) state of diffuse, or free-floating, anxiety and worry that is not attached to specific situations or objects.

Obsessive-compulsive disorder

individuals with these disorders feel compelled to act in a rigid, repetitive way to reduce their anxiety or distress, for example, by excessive cleaning, washing or checking, by hoarding objects, or by being excessively preoccupied with certain body parts

in spite of having their own separate group in DSM-5, these disorders are still seen as strongly related to anxiety

Obsessions are repetitive and unwelcome thoughts, images or impulses that invade consciousness, are often abhorrent to the person and are very difficult to dismiss or control.

Compulsions are repetitive behavioural responses

that can be resisted only with great difficulty.

Compulsions may be overt (observable by others) or covert.

Once the mother performed her compulsive cleaning acts, she was relatively free from anxiety, at least until the thoughts of contamination intruded once more.

Louis Pasteur’s discovery of a process for eliminating destructive micro-organisms and limiting fermentation in milk, beer and other liquids. His tireless work on this invention was fuelled in part by his own obsession about contamination and infection.

Like phobic avoidance responses, compulsions are strengthened through a process of negative reinforcement because they allow the person to avoid anxiety (Jenike, 1998).

Post-traumatic stress disorder

strongly related to anxiety

PTSD is a severe disorder that can occur in people who have been exposed to traumatic life events

Intrusion symptoms, such as intrusive images, memories and dreams, that cause the person to re-experience the traumatic event as if it were recurring again and again.  
2\. Persistent avoidance of any reminders of the traumatic event.  
3\. Negative changes in cognition and mood, which can involve fear, helplessness, self-blame, anger or hopelessness.  
4\. Changes in arousal and reactivity, which can manifest in sleep disturbance, poor concentration, hypervigilance, exaggerated startle responses, and reckless or impulsive behaviours.

the risk of PTSD increased with combat exposure

Traumas caused by human actions, such as war, rape and torture, are 5 to 10 times more likely to precipitate PTSD than are natural disasters, such as hurricanes and earthquakes

Compared with men, women exhibit twice the rate of PTSD following exposure to traumatic events

PTSD may increase vulnerability to the subsequent development of other disorders.

Causal factors in anxiety and related disorders

Biological factors

indicate a genetic predisposition, the concordance rate even in identical twins is far from 100 per cent, indicating the significance of psychological, environmental and social factors.

abnormally low levels of inhibitory GABA activity in these arousal areas may cause some people to have highly reactive nervous systems that quickly produce anxiety responses to stressors

patients with a history of panic attacks have a 22 per cent lower concentration of GABA in the occipital cortex than age-matched controls without panic disorder

more susceptible to classically conditioned phobias because they already have a strong unconditioned arousal response in place, ready to be conditioned to new stimuli.

serotonin

also involved in the anxiety disorders

women exhibit anxiety disorders more often than men do

sex difference emerges as early as 7 years of age.

findings suggest a sex-linked biological predisposition for anxiety disorders, but social conditions that give women less power and personal control may also contribute

biological, psychological, and environmental and social factors combine in complex ways.

Psychological factors

Psychodynamic theories

According to Freud, neurotic anxiety occurs when unacceptable impulses threaten to overwhelm the ego’s defences and explode into consciousness or action.

The role of learning

From the behavioural perspective, classical conditioning, observational learning or operant conditioning can all contribute to the development of an anxiety disorder.

phobias can also be acquired through observational learning

televised images of aeroplane crashes evoke high levels of fear in some people

operant conditioning also plays a role.

obsessive-compulsive mother’s scrubbing ritual reduces anxiety about contamination, and this reduction in anxiety acts as a negative reinforcement for her ritual.

In the case of agoraphobia, remaining at home also serves as a safety signal, a place where the person is unlikely to experience a panic attack

successful avoidance, while producing an immediate positive benefit, prolongs the problem in the long run.

Cognitive factors

panic attacks can be triggered by exaggerated misinterpretations of normal anxiety symptoms

Helping panic patients replace such mortal-danger appraisals with more benign interpretations of their bodily symptoms (e.g. ‘It’s only a bit of anxiety, not a heart attack’) can result in a marked reduction in panic attacks

Sociocultural factors

culture-bound disord ers , which occur only in certain locales.

Taijin kyofushu

koro

anorexia nervosa has a strong phobic component

the fear of getting fat

It also has obsessive-compulsive elements

Somatic symptom and related disorders involve physical complaints or disabilities that suggest a medical problem but which do not always have a known biological cause and are not produced voluntarily by the person.

conversion disorder , in which serious neurological symptoms, such as paralysis, loss of sensation or blindness, suddenly occur.

exhibit la belle indifference, a strange lack of concern about their symptoms and their implications

Dissociative disorders involve a breakdown of normal personality integration, resulting in significant alterations in memory or identity.

dissociative amnesia , a person responds to a stressful event with extensive but selective memory loss.

dissociative fugue , a more profound dissociative state in which a person loses all sense of personal identity, gives up her or his customary life, wanders to a new faraway location and establishes a new identity.

the fugue ends when the person suddenly recovers his or her original identity and ‘wakes up’, mystified and distressed at being in a strange place under strange circumstances.

dissociative identity disorder (DID) (formerly called multiple personality disorder), two or more separate personalities coexist in the same person.

trauma-dissociation theory , the development of new personalities occurs in response to severe stress.

mood disorders is a term referring to a variety of disorders that can involve either depression or mania, or both

high comorbidity (co-occurrence) involving anxiety and mood disorders.

In clinical depression, however, the frequency, intensity and duration of depressive symptoms are out of proportion to the person’s life situation.

major depression , an intense state of sadness (dysphoria) and/or lack of ability to feel positive emotion (anhedonia) that leaves them unable to function effectively in their lives.

Other people exhibit a less intense form of depression that has less dramatic effects on personal and occupational functioning, but continues for a significant amount of time largely unabated.

This less intense but longer-lasting form of depression, occurring for years on end with some intervals of normal mood that never last more than a few weeks or months, was labelled ‘dysthymic disorder

disorder’ in DSM-IV-TR (APA, 2000) and is now labelled ‘persistent depressive disorder’ in DSM-5

negative mood state is the core feature of depression

anxiety disorders retain their capacity to experience pleasure, depressed people lose it

Although depression is primarily a disorder of emotion or mood, there are three other types of symptoms: cognitive, motivational and somatic

Cognitive symptoms

difficulty concentrating and making decisions.

Motivational symptoms

an inability to get started and to perform behaviours that might produce pleasure or accomplishment.

Somatic (bodily) symptoms

Figure 15.15

Facets of depression

Bipolar disorder

bip olar I disorder , depression alternates with periods of mania , a state of highly excited mood and behaviour that is quite the opposite of depression.

In a manic state, the mood is euphoric and cognitions are grandiose.

The 19th-century composer Robert Schumann produced 27 works during a one-year manic phase, but his productivity ground to a halt when he sank back into the depressive phase of his bipolar disorder

hypomanic episodes alternating with depressive episodes.

not severe enough in themselves to cause impairment

bipolar II disorder , involving hypomanic and depressive episodes, is just as impairing as bipolar I disorder. This is because bipolar II disorder tends to be associated with more severe and chronic depressive episodes, compared to bipolar I.

Prevalence and course of mood disorders

1 in 20

No age group is exempt from depression

Prevalence of depressive disorders is similar across socioeconomic and ethnic groups, but there is a major sex difference in our culture.

men and women do not differ in the prevalence of bipolar disorder, women appear to be almost twice as likely as men to suffer a depressive disorder

The prevalence of depression increases markedly during adolescence for both genders, but especially so among young women.

Women are most likely to suffer their first episode of depression in their 20s, men in their 40s

Figure 15.18 What follows the first episode of major depression?

Causal factors in depressive and bipolar disorders

Biological factors

Both genetic and neurochemical factors have been linked to depression.

What is likely to be inherited is a predisposition to develop a depressive disorder, given certain kinds of environmental factors such as significant losses and low social support

the behavioural inhibition system (neuroticism) and the behavioural activation system (extraversion), are involved in the development of mood disorders

(BAS) is reward-oriented and activated by cues that predict future pleasure, whereas the behavioural inhibition system (BIS) is pain-avoidant and generates fear and anxiety

Depression is predicted by high BIS sensitivity and low BAS activity.

Mania, on the other hand, is linked to high reward-oriented BAS functioning, and scores on the personality variable of extraversion (tied heavily to the BAS) predict the future development of bipolar mania

depression

underactivity in a family of neurotransmitters that include norepinephrine (noradrenaline), dopamine and serotonin.

Psychological factors

Personality-based vulnerability

early traumatic losses or rejections create vulnerability for later depression by triggering a grieving and rage process that becomes part of the individual’s personality

Subsequent losses and rejection reactivate the original loss and cause a reaction not only to the current event but also to the unresolved loss from the past.

Cognitive processes

depressive cognitive triad involves negative thoughts concerning (1) the world, (2) oneself and (3) the future

Depressed people

detect pictures of sad faces

and remember them better

perceptual and memory sensitivity to negative elements,

more likely to recall memories of negative events.

depressive attributional pattern , attributing successes or other positive events to factors outside the self while attributing negative outcomes to personal factors

At all age levels, low self-esteem predicted later depressive episodes

Figure 15.21 The depressive attributional pattern

learned helplessness theory , holds that depression occurs when people expect that bad events will occur and that there is nothing they can do to prevent them or cope with them

chronic and intense depression occurs as the result of negative attributions for failures that are personal or internal (‘It’s all my fault’), stable (‘I’ll always be this way’) and global (‘I’m a total loser’).

bipolar disorder

autonomy

high performance standards

tendency toward self-criticism when goals are not obtained

bipolar group membership but also the occurrence of future hypomanic episodes.

Learning and environmental factors

depression

people stop performing behaviours that previously provided reinforcement, such as hobbies and socialising.

generate additional negative life events through their negative moods, pessimism and reduced functioning

elicit anxious, depressed and hostile reactions from others

diminishes social support still further and may eventually cause depressed people to be abandoned by those who are most important to them

reductions in social support are a good predictor of subsequent depression

setting positive goals

positive reinforcement produced by this process of behavioural activation will begin to counteract the depressive affect, undermine the sense of hopelessness that characterises depression and increase feelings of personal control over the environment

children of depressed parents often experience poor parenting and many stressful experiences as they grow up.

Figure 15.22 Lewinsohn’s behavioural model of depression

Sociocultural factors

depressive disorders is far lower in Hong Kong and Taiwan than in Western nations

strong social support from family

reduce the negative impact of loss and disappointments

Feelings of guilt

personal inadequacy

Western countries

somatic symptoms of fatigue

loss of appetite

sleep difficulties

Latin, Chinese and African cultures

many depressed people consider suicide as a way to escape the unhappiness of their lives.

triple vulnerability model of emotional disorders , it draws on the biological, psychological, and environmental and social levels of analysis.

genetic factors that favour ascendancy of the BIS over the BAS

SCHIZOPHRENIA

Schizophrenia includes severe disturbances in thinking, speech, perception, emotion and behaviour

the term means ‘split mind’, which has often led people to confuse schizophrenia with dissociative identity disorder (‘split personality’) or with a Dr Jekyll–Mr Hyde phenomenon.

Characteristics of schizophrenia

delusions , false beliefs that are sustained in the face of evidence that would normally be sufficient to negate these beliefs

a delusion of persecution

a delusion of grandeur

hallucinations , false perceptions that have a compelling sense of reality

Auditory hallucinations

visual and tactile hallucinations

blunted affect, manifesting less sadness, joy and anger than most people

flat affect, showing almost no emotions at all

Subtypes of schizophrenia

DSM-IV-TR

Paranoid schizophrenia

Disorganised schizophrenia

Catatonic schizophrenia

Undifferentiated schizophrenia

positive symptoms , such as delusions, hallucinations and disordered speech and thinking

pathological extremes of normal processes

negative symptoms —an absence of normal reactions, such as lack of emotional expression, loss of motivation and an absence of speech

positive-symptom and negative-symptom subtypes

Negative symptoms are likely to be associated with a long history of poor functioning prior to diagnosis and with a poor outcome following treatment

positive symptoms

are associated with good functioning prior to breakdown and a better prognosis for eventual recovery

1 per cent of the population

occupy half of all residential mental health services in Australia

About 10 per cent of people with schizophrenia remain permanently impaired,

Causal factors in schizophrenia

Biological factors

Genetic predisposition

Brain abnormalities

According to the neurodegenerative hypothesis, destruction of neural tissue can cause schizophrenia

brain atrophy

cerebral cortex and limbic system, together with enlarged ventricles

centred in brain regions that influence cognitive processes and emotion

thalamus, which collects and routes sensory input to various parts of the brain

these patients have a poorer chance of recovery than those with the

positive-symptom pattern

Biochemical factors

dopamine hypothesis , the symptoms of schizophrenia— particularly positive symptoms—are produced by overactivity of the dopamine system in areas of the brain that regulate emotional expression, motivated behaviour and cognitive functioning

more dopamine receptors on neuron membranes

overreactive to dopamine stimulation

antipsychotic drugs used to treat schizophrenia

reduce dopamine-produced synaptic activity

deficiency of neural input from cortical areas also plays a role

The biochemical and brain findings concerning schizophrenia are intriguing. What is not clear is whether they cause the disorder or are caused by it. Future research is almost certain to reveal other biological bases for the complex disorders of schizophrenia.

Psychological factors

regression , in which a person retreats to an earlier and more secure (even infantile) stage of psychosocial development in the face of overwhelming anxiety.

stimulus overload produces distractibility, thought disorganisation and the sense of being overwhelmed by disconnected thoughts and ideas.

Environmental factors

events tend to cluster in the 2 or 3 weeks preceding the ‘psychotic break’,

Psychotic individuals reacted to their stressors with more intense negative emotions, suggesting that emotional overreactivity may be a vulnerability factor

an individual must have a biological vulnerability factor in order to be damaged by stressful family events to such a degree.

These behavioural oddities may not only reflect a vulnerability factor, but they may also help create environmental stress by evoking negative reactions from others.

Sociocultural factors

social causation hypothesis attributes the higher prevalence of schizophrenia to the higher levels of stress that low- income people experience

social drif t hypothesis proposes that as people develop schizophrenia, their personal and occupational functioning deteriorates, so that they drift down the socioeconomic ladder

prevalence of schizophrenia is not dramatically different throughout the world

recovery is greater in some developing countries than in the developed nations.

stronger community

greater social support

PERSONALITY DISORDERS

personality disorders exhibit stable, ingrained, inflexible and maladaptive ways of thinking, feeling and behaving.

10 personality disorders in the current psychiatric diagnostic codes.

dramatic and impulsive behaviours, anxious and fearful behaviours, and odd and eccentric behaviours.

Table 15.2

antisocial personality disorder (APD) seem to lack a conscience; they exhibit little anxiety or guilt and tend to be impulsive and unable to delay gratification of their needs.

Males outnumber females three to one in this diagnostic group

In the past, individuals with APD were referred to as psychopaths or sociopaths

Psychopathy represents a personality dimension

antisocial personality disorder is defined in the DSM-5 predominantly in terms of observable, specific behaviours.

two behavioural clusters associated with psychopathy

selfishness, callousness and interpersonal manipulation, and

impulsivity, instability and social deviance

To be diagnosed with APD, a person must be at least 18 years of age. However, the diagnostic criteria also require substantial evidence of antisocial behaviour before the age of 15

habitual lying, early and aggressive sexual behaviour, excessive drinking, theft, vandalism and chronic rule violations at home and school.

Causal factors

Biological factors

higher rates of concordance for antisocial behaviour in identical twins than in fraternal twins

Adoption

the criminality rate was nearly twice as high if the biological father had a criminal record,

relative absence of anxiety and guilt that seems to characterise APD

dysfunction in brain structures that govern emotional arousal and behavioural self-control, particularly the amygdala and the prefrontal cortex

MRIs also reveal that antisocial individuals have subtle neurological deficits in the prefrontal lobes—the seat of executive functions such as planning, reasoning and behavioural inhibition; these neurological deficits are associated with reduced autonomic activity

wired differently at a neurological level

with less arousal and greater impulsiveness to both pleasurable and unpleasant stimuli

Psychological and environmental factors

Psychodynamic

lacking a conscience

Psychoanalytic

lack anxiety and guilt because they did not develop an adequate superego

absence of a well-developed superego, the restraints on the id are reduced

adult figures

either physically or psychologically unavailable to the child

absence of the father

higher incidence of antisocial symptoms in children, even when socioeconomic status is equated

Cognitive theorists

consistent failure to think about or anticipate the long-term negative consequences of their acts.

behave impulsively

only of what they want at that moment

develop the cognitive controls (i.e. the executive functions

Learning through modelling

parents exhibit a good deal of aggression and are inattentive to their children’s needs

exposure to deviant peers

prefrontal cortex is the site of executive functions

Borderline personality disorder

About two-thirds of those diagnosed are women

borderline personality disorder (BPD) refers to a collection of symptoms characterised primarily by serious instability in behaviour, emotion, identity and interpersonal relationships.

emotional dysregulation, an inability to control negative emotions in response to stressful life events

intense and unstable personal relationships

chronic feelings of extreme anger, loneliness and emptiness, as well as momentary losses of personal identity

impulsive behaviour such as running away, promiscuity, binge eating and drug abuse

self-mutilation and suicide attempts

BPD is highly associated with a number of other disorders, including mood disorders, PTSD, eating disorders and substance-abuse disorders.

interpersonal strife, sexual and physical abuse, and inconsistent parenting

someone had treated them in a malevolent manner or had injured them emotionally or physically

viewed potential helpers as far less helpful to them

parents are described as abusive, rejecting and non-affirming

behaviours tend to evoke negative reactions and rejection from others, affirming their sense of worthlessness and their view of the world as malevolent.

extreme love and clinging dependence to intense hatred or feelings of abandonment

splitting , the failure to integrate positive and negative aspects of another’s behaviour (e.g. a parent who is usually accepting but sometimes voices disapproval) into a coherent whole.

Table 15.3 From conscientious personality to obsessive–compulsive personality disorder: a dimensional view

neurodevelopmental disorders are a group of disorders that are known to always manifest at an early age, usually before or soon after the child enters school.

This group includes intellectual developmental disorder, communication disorders, neurodevelopmental motor disorders and specific learning disorders, as well as autism spectrum and attention-deficit/hyperactivity disorder (ADHD)

attention-deficit/hyperactivity disorder (ADHD) , problems may take the form of inattention, hyperactivity/impulsivity or a combination of the two.

for 50 to 80 per cent, the problems persist into adolescence and, for 30 to 50 per cent, into adulthood

Overall, adults with ADHD have more occupational, family, emotional and interpersonal problems.

the precise causes of ADHD are unknown

concordance rates are higher in identical than in fraternal twins

adoption studies of children with ADHD, the children’s biological parents are more likely to have ADHD than the adoptive parents

EEG studies

have failed to reveal consistent differences between people with ADHD and control groups

autism spectrum disorder (ASD) . The four previous DSM-IV-TR (A PA, 2000) categories, which included autistic disorder (or autism) and Asperger’s disorder, are now seen as reflecting a single condition with different levels of symptom severity in two core areas. These two core areas entail (1) difficulties in social interactions and (2) a pattern of repetitive behaviours, interests and activities.

Lack of social responsiveness to others is a central feature of the disorder.

Language and communication difficulties are also common

Sameness and routine are very important

A few people with ASD

exhibit extraordinary savant (from the French word for ‘wise’ or ‘learned’) abilities.

Sometimes these skills give the impression of superior intelligence, even in people who have intellectual disability

Today, it is widely accepted that autism has a biological basis

anomalies in the structures and functioning of the brain

brains of children with ASD are 5 to 10 per cent larger than average at 18 months to 4 years of age.

accelerated pruning of neural connections during early life, and prefrontal-cortex development is abnormal, too.

abnormal development in the cerebellum,

Genetic factors

there may be four to six major genes and 20 to 30 others that contribute to a lesser degree.

different genes may be involved for boys than for girls

concordance is highest in identical twins

there may be multiple interacting genes.

many relatives of children with ASD, though not manifesting the disorder themselves, have unusual personality characteristics that parallel autism, including aloofness and very narrow and specialised interests

theory of mind

Normally, children become aware of some characteristics of other people’s thinking by the age of 3 or 4

difficult for them to communicate with others or understand how other people might be internally reacting to them

Theory of mind deficits could severely impair language and social development, and they are a strong focus of current research on autism.