---
title: "Topic 2: Personality"
output: html_document
---

### Introduction

- The psychodynamic perspective on personality, originated from the work of Sigmund Freud, emphasizes unconscious psychological processes (such as wishes and fears) and the impact of childhood experiences on adult personality.
- This perspective has been both influential and controversial, with some of its concepts being supported by empirical evidence while others are not.
- The psychodynamic theory continues to play an important role in psychology and many related disciplines, such as developmental psychology, social psychology, sociology, and neuroscience.
- The theory has evolved over time and now includes innovative approaches such as object relations theory and neuropsychoanalysis.
- In the context of personality, psychodynamic theory can help one understand why they may do things that don't make sense, by exploring unconscious thoughts and emotions.

## Core Assumptions of the Psychodynamic Perspective {.tabset}

The core assumptions of the psychodynamic framework are unique from the componenets of other personality ideas.

### 1. Primacy of the Unconscious

- The perspective on unconscious psychological processes is a central aspect of psychodynamic theory.
- The idea is that unconscious thoughts, feelings, and impulses influence our behaviour, even though we may not be aware of them.
- For example, a person may have unconscious fears or desires that drive their behaviour, even if they don't consciously understand what is motivating them.
- Psychoanalytic therapy aims to bring these unconscious processes to consciousness, where they can be better understood and addressed.
- The belief in the importance of unconscious psychological processes continues to be a defining feature of the psychodynamic perspective on personality.

***

### 2. Critical Importance of Early Experiences

- The psychodynamic theory holds that childhood experiences and unconscious psychological processes play a crucial role in shaping adult personality.
- According to this perspective, early childhood experiences, including even those that occur in the first few weeks or months of life, can have a lasting impact on a person's personality development and dynamics.
- The emphasis on early childhood events sets the psychodynamic theory apart from other models of personality development, which also consider early experiences but do not place as much emphasis on their impact.
- The theory also posits that experiences outside the normal range, such as the loss of a parent or sibling at an early age, can have a particularly strong impact on personality development.

***

### 3. Psychic Causality {-}

- The third core assumption of psychodynamic theory is that nothing in mental life happens by chance—that there is no such thing as a random thought, feeling, motive, or behaviour.
- This has come to be known as the *principle of psychic causality*, and though few psychologists accept the principle of psychic causality precisely as psychoanalysts conceive it, most theorists and researchers agree that thoughts, motives, emotional responses, and expressed behaviours do not arise randomly, but always stem from some combination of identifiable biological and psychological processes (Elliott, 2002; Robinson & Gordon, 2011).

***

## The Evolution of Psychodynamic Theory {.tabset}

- Freud’s background in neurology is the basis for the first incarnation of psychoanalytic theory being regarded as primarily biological.
- Freud set out to explain psychological phenomena in terms that could be linked to neurological functioning as it was understood in his day.
- Because Freud’s work in this area evolved over more than 50 years (he began in 1885, and continued until he died in 1939), there were numerous revisions along the way.
- Thus, it is most accurate to think of psychodynamic theory as a set of interrelated models that complement and build upon each other.
- Three are particularly important: the topographic model, the psychosexual stage model, and the structural model.

### The Topographic Model

- The topographic model describes the unconscious, preconscious, and conscious as different regions of the mind.
- The unconscious is seen as the largest (and most primitive, and controversial) part of the psyche, contains all the instinctual drives, repressed material, and anxiety-producing material (such as sexual impulses and aggressive urges) that are deliberately repressed, meaning they are kept outside of conscious awareness as a form of self-defence because they make you uncomfortable.
- The preconscious is a more advanced part of the mind, which contains thoughts and feelings that are not currently in conscious awareness but can be brought to consciousness if needed.
- The conscious is the smallest part of the mind and contains all the thoughts, feelings, and experiences that are currently in awareness.
- The idea of the unconscious mind continues to be debated in psychology, with some researchers finding evidence for its existence and others believing that unconscious processing can be explained without it.
- The terms conscious, preconscious, and unconscious continue to be used today and research has provided some support for Freud’s thoughts regarding conscious and preconscious processing.
- However, the idea of a Freudian unconscious repository of repressed wishes and impulses remains controversial.

***

### The Psychosexual Stage Model

- The psychosexual stage model proposed by Freud in 1905 argues that human personality development progresses through a sequence of stages (driven by sexual and aggressive energy (libido)), each with its own unique challenge and mode of sexual gratification from infancy to adulthood.
- The stages are oral, anal, Oedipal, latency, and genital. Fixation at a particular stage due to frustration or over gratification is thought to result in a dependent (oral), controlling (anal), or aggressive/competitive (Oedipal) personality style.
- Each stage is marked by the appearance of a new erogenous zone (an area of the body that is particularly sensitive to sexual stimulation) and is associated with a specific conflict that must be resolved.
- According to the model, if the individual experiences trauma or fixates at any of the stages, this can result in the development of certain personality traits and psychological disorders.
- The psychosexual stage model and its relationship to personality development remain a significant part of psychoanalytic theory.

***

### The Structural Model

- The structural model describes the psyche as consisting of three parts: the id, the ego, and the superego.
- The id is the unconscious part of the psyche that is driven by instinctual drives and impulses.
- The ego is the conscious part of the psyche that mediates between the impulses of the id and the demands of reality.
- The superego is the moral component of the psyche, which internalizes the values and norms of society and provides a sense of right and wrong.
- According to the structural model, the dynamic interplay between the id, ego, and superego results in the development of the individual’s personality and behaviour.

***

### The Ego and its Defences {-}

Common Ego Defences in Psychodynamic Theory

- **Repression**: The unconscious removal of upsetting thoughts and feelings from conscious awareness. Example: A person blocks out memories of childhood abuse.
- **Denial**: The conscious ignoring the implications of a painful event. Example: A person with a substance abuse problem says "I'm fine—even though people complain about my drinking, I never miss a day of work."
- **Projection**: Attributing one's own unacceptable thoughts or feelings to others. Example: A person who has aggressive impulses accuses others of being hostile.
- **Displacement**: Shifting one's emotional responses from a threatening target to a less threatening substitute. Example: A person who is angry with their boss takes out their frustration on their spouse.
- **Regression**: Reverting to an earlier stage of development in response to stress. Example: An adult who is feeling overwhelmed may start sucking their thumb.
- **Rationalization**: Offering self-justifying explanations in place of the real reasons for one's behavior. Example: A person who was fired for poor performance says that the job wasn't a good fit for them anyway.
- **Sublimation**: Channelling unacceptable impulses into socially acceptable behavior. Example: A person who has aggressive impulses becomes a professional boxer.
- These are just a few of the many ego defenses that have been identified in psychodynamic theory. The use of these defences is seen as a way for the ego to manage anxiety and protect itself from stress, but at the same time, they can also lead to the distorting of reality and the perpetuation of problematic behavior patterns.

***

## Psychodynamic Theories: Where Are We Now? {.tabset}

Empirical Testing of Psychodynamic Concepts: Research has been conducted to empirically test psychodynamic concepts and theories, such as the concept of transference, the role of unconscious processes in personality, and the effects of childhood experiences on adult behavior. This research has provided some support for psychodynamic concepts, but it has also led to modifications and revisions of these concepts.

Psychoanalysis and Culture: The influence of culture on psychoanalytic theory has been recognized and studied. Cultural values, beliefs and norms can shape the way psychoanalytic concepts are understood and applied.

Neuroscience and Psychodynamics: Advances in neuroimaging and neuropsychology have opened up new opportunities to explore the relationship between brain and behavior, and the role of unconscious mental processes in personality. However, the relationship between psychodynamics and neuroscience is still being explored, and the field continues to face challenges in integrating these two perspectives.

### Object Relations Theory and the Growth of the Psychodynamic Perspective

- This perspective focuses on the role of early childhood relationships in shaping personality and shaping adult relationships. It emphasizes the importance of the child’s experience of being loved, understood and emotionally connected to important caretakers.
- According to this theory, a child's relationship with his or her parents is crucial to the formation of self-esteem and the capacity for healthy relationships in adulthood.
- The child's interactions with his or her parents and other significant figures are seen as the building blocks of the child's inner world, including mental representations of self and others, as well as unconscious fantasies, desires, and anxieties.
- Also emphasizes the importance of the interpersonal context in shaping personality development. This means that relationships, rather than individual factors, are seen as the key drivers of personality development and change.
- Overall, object relations theory offers a nuanced and sophisticated perspective on the development of personality, recognizing the importance of both early childhood experiences and ongoing relationships in shaping the self and personality.

***

### Empirical Research on Psychodynamic Theories

- Research has been conducted to empirically test psychodynamic concepts and theories, such as the concept of transference, the role of unconscious processes in personality, and the effects of childhood experiences on adult behavior.
- This research has provided some support for psychodynamic concepts, but it has also led to modifications and revisions of these concepts.
- Psychoanalysis and culture is another growing area of interest in contemporary psychodynamic theory.
- Psychoanalysis has always been concerned with the role of culture in shaping personality, but it has historically focused on the influence of the cultural forces (such as media, religion, politics, and economics) that shape our unconscious desires and conflicts.
- Today, psychoanalytic research also considers the ways in which culture shapes the way we understand and treat mental illness.
- In particular, researchers are exploring how cultural and ethnic differences affect the way people experience and express emotions, relationships, and psychological distress.
- Advances in neuroscience have created new opportunities and challenges for psychodynamic theory. The increasing ability to measure brain activity has created the possibility of gaining new insights into unconscious mental processes, including the workings of the ego, the id, and the superego. However, neuroscience has also created challenges for psychodynamic theory, because it has revealed that some traditional psychoanalytic concepts, such as the notion that the unconscious is inaccessible to conscious awareness, may be too simplistic (Kihlstrom, 2010). Nonetheless, the integration of psychodynamic theory with neuroscience has the potential to advance our understanding of mental processes, personality development, and the treatment of psychological disorders.

***

### Psychoanalysis and Culture

The influence of culture on psychoanalytic theory has been recognized and studied. Cultural values, beliefs and norms can shape the way psychoanalytic concepts are understood and applied.

***

### Neuroscience and Psychodynamics

Advances in neuroimaging and neuropsychology have opened up new opportunities to explore the relationship between brain and behavior, and the role of unconscious mental processes in personality. However, the relationship between psychodynamics and neuroscience is still being explored, and the field continues to face challenges in integrating these two perspectives.

***

### The Opportunities and Challenges of Neuroscience

- The integration of psychodynamic and neuroscientific perspectives has brought new opportunities for exploring the underlying neural mechanisms of psychological processes, such as emotions, thoughts, and behaviours.
- It has provided a new understanding of the relationship between brain and mental processes and has advanced the treatment of mental disorders.
- Despite these advancements, there are still challenges in the integration of psychodynamic and neuroscience perspectives, such as the different theoretical frameworks and languages used in both fields.
- The integration of psychodynamic principles with findings from neuroscience continues to offer a promising direction for future research in the field of psychology.

***

### Looking Ahead: Psychodynamic Theory in the 21st Century (and Beyond) {-}

- The psychodynamic perspective has been a major force in psychology for more than a century and has had a lasting impact on the field.
- Despite criticism and controversy, the psychodynamic perspective has been able to evolve and adapt to new ideas, findings, and social forces.
- The theory continues to be relevant in addressing a wide range of topics such as normal and pathological functioning, motivation and emotion, childhood and adulthood, individual and culture.
- The integration of psychodynamic concepts with findings from neuroscience has also led to the development of neuropsychoanalysis, which has further expanded our understanding of human behavior and mental functioning. Overall, the psychodynamic perspective offers a comprehensive and integrative approach to understanding human personality and behavior, making it a valuable contribution to the field of psychology.

***

## Personality Traits {.tabset}

- The trait approach to personality psychology aims to understand individual differences in personality by focusing on personality traits, which are basic dimensions along which people differ.
- Traits are thought to be consistent, stable, and reflective of individual differences.
- Gordon Allport and Henry Odbert's lexical hypothesis guided their approach to finding the major traits by searching dictionaries for personality descriptors and using statistical techniques to determine which words went together.
- The goal was to identify the basic dimensions underlying the many words we use to describe people and reduce the number of traits.
- The trait approach has been successful in identifying the five-factor model or the "big five" traits:
  - Extroversion,
  - Conscientiousness,
  - Agreeableness,
  - Neuroticism, and
  - Openness to Experience.

### The Five-Factor Model of Personality

- The Big Five or Five-Factor Model of personality is the most widely accepted system for describing personality traits.
- The five traits are Openness, Conscientiousness, Extroversion, Agreeableness, and Neuroticism (OCEAN).
- These traits describe stable patterns of behavior that persist over long periods of time and have broad-ranging consequences for various areas of life.
- For instance, Conscientiousness has been found to predict success in college, job performance, and health.
- There is growing interest in personality psychology among psychologists who work in applied settings like health psychology and organizational psychology.

***

### Facets of Traits (Subtraits)

- The Big Five traits are a widely accepted framework for summarizing a person's personality.
- They are, however, considered broad and do not capture the complexity and specificity of an individual's behavior and thoughts.
- To address this, lower-level units of personality known as facets have been proposed.
- Facets provide more specific descriptions of a person's characteristics and are useful in providing a more nuanced understanding of an individual's personality.
- Different facets within a trait tend to go together and can be used to predict how a person might behave in different situations.
- The list of facets is not universally accepted, and different researchers may propose different lists. Nevertheless, facets provide valuable information and add to our understanding of a person's personality beyond just their Big Five trait scores.

***

### Other Traits Beyond the Five-Factor Model

-Not all researchers agree on the number and composition of personality traits, and there have been other models proposed with different traits.
- For example, Hans Eysenck proposed that Extraversion and Neuroticism are the two most important traits and linked them to differences in people's biology.
- The HEXACO model adds Honesty-Humility as a sixth dimension of personality.
- Despite the popularity of the Big Five, there are still debates on the exact number and composition of the traits that are most important in understanding personality.
- Additionally, there are many other traits that have been studied by researchers in the field of personality psychology that are not included in comprehensive models like the Big Five.

***

### The Person-Situation Debate and Alternatives to the Trait Perspective {-}

- The person-situation debate in personality psychology arose from the publication of Walter Mischel's book "Personality and Assessment" in 1968.
- Mischel challenged the traditional trait perspective of personality by suggesting that people's behavior is not consistently consistent across different situations.
- He believed that psychologists should focus on people's unique reactions to specific situations rather than studying broad, context-free traits.
- Subsequent research to address this theory showed that on average, the effect of the situation is about as large as that of personality traits.
- Personality traits still provide an indication of how people will act on average, but they are not always good predictors of specific behavior in a given situation.
- Most modern personality researchers acknowledge the value of both broad personality traits and narrower units studied by Mischel.

***

## Personality Assessment {.tabset}

- The study of personality is diverse and encompasses a broad range of traits and characteristics.
- Different theoretical models have led to different approaches for measuring these characteristics.
- *Humanistic* models focus on individuals' goals and motivations, so asking them directly is a good approach.
- *Psychodynamic* models suggest that unconscious processes drive behaviour, so researchers adopt indirect approaches to identify these factors.

### Objective Tests

- Objective tests have several advantages in personality assessment:
  - Relatively inexpensive and easy to administer, 
  - Can be administered to large groups of people, and 
  - Are usually highly reliable (i.e., they provide consistent scores over time).
- However, objective tests have certain limitations as well:
  - Limited in their ability to capture the complexity of individual differences,
  - May not always provide a complete picture of an individual's personality,
  - Can be affected by social desirability bias (where people tend to respond in a way that they believe is socially desirable or acceptable), rather than providing a true representation of their personality.
- Despite these limitations, objective tests continue to be widely used in personality assessment due to their ease of use, reliability, and versatility.

### Basic Types of Objective Tests

#### Self-Report Measures

- Objective personality tests are widely used to assess personality, and can be self-administered or performed by a psychologist.
- Self-report tests, in which individuals describe themselves, are the most widely used type of objective test.
- They offer advantages such as:
  - cost-effectiveness, and
  - simplicity and access to a wealth of information.
- Self-reported personality has been shown to have significant validity in relation to various important outcomes, such as academic and job performance, occupational attainment, divorce, and mortality, as well as links to psychopathology.
- Self-reported personality, however, is limited by:
  - The possibility of socially desirable responding,
  - Self-enhancement bias, and
  - The reference group effect.

#### Informant Ratings

- Informant personality ratings are a method of assessing someone's personality where the information is gathered from a person who knows the person being rated well, such as a parent, teacher, spouse, friend, or boss.
- These ratings are particularly useful when self-ratings are not possible or not reliable.
- Informant ratings offer advantages such as:
  - Being based on the informant's observation of the person's behaviour, and
  - Being less likely to be distorted by defensiveness.
- Informant ratings can also be limited by:
  - The amount of information the informant has about the person, and
  - Are subject to response biases (the reference group effect, and the tendency for informants to produce overly favourable ratings).
  
### Other Ways of Classifying Objective Tests

- Personality tests differ on two dimensions:
  - *Comprehensiveness* (measure a single attribute (e.g. Toronto Alexithymia Scale, Rosenberg Self-Esteem Scale), and
  - *Breadth of the target characteristics* (e.g. California Psychological Inventory, HEXACO Personality Inventory, Multidimensional Personality Questionnaire, NEO Personality Inventory-3, Personality Research Form, 16PF).
- There are different levels of breadth or generality at which personality characteristics can be classified.
- Some models emphasize broad, "big" traits, while others focus on more specific characteristics.
- Some popular personality instruments assess only broad traits, while others assess a large number of more specific characteristics.
- Some instruments are explicitly designed to provide coverage of both general and specific trait characteristics.

### Projective and Implicit Tests

- *Projective* tests are based on the belief that unconscious needs, feelings, and experiences can be revealed by having people describe or interpret ambiguous stimuli.
- Examples of projective tests include the Rorschach Inkblot Test and the Thematic Apperception Test (TAT).
- Projective tests can be cumbersome to administer and score, but they can provide information about implicit motives that is not easily obtained from objective measures.
- The TAT has shown significant validity in measuring the need for achievement, while the validity of the Rorschach has been a matter of controversy.

- *Implicit* measures of personality are based on the idea that people form automatic or implicit associations between certain concepts based on their previous experience and behaviour.
- These measures assess the strength of associations between concepts and can be used to predict behavior, even after controlling for scores on objective measures of personality.
- While validity evidence for these measures is still limited, the results to date are promising.

### Behavioral and Performance Measures

- Behavioural measures of personality involve directly observing and measuring people's behaviour in natural settings.
- This approach offers several advantages, such as avoiding response biases and studying people in their daily lives.
- However, it is more labour-intensive than other methods and generates a large set of data that must be scored reliably.
- Also, the small samples of behavior collected may not reflect a person's true characteristics accurately, as they can be influenced by transient factors such as a participant's level of stress, and their quality of sleep the previous night.
